<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class HotelMadinahSeeder extends Seeder
{
    /**
     * Run the database seeds. Kota = Madinah (nama_kota di kota_m).
     */
    public function run(): void
    {
        $kotaId = DB::table('kota_m')->where('nama_kota', 'Madinah')->value('id');
        if (!$kotaId) {
            return;
        }

        $now = Carbon::now();

        $hotels = [
            [
                'is_active' => true,
                'nama_hotel' => 'Sofitel',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => 5.0,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => true,
                'nama_hotel' => 'Al Haram Dar Al Eiman',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => 5.0,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => true,
                'nama_hotel' => 'Millenium Al Aqeeq',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => 5.0,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => true,
                'nama_hotel' => 'Taibah font',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => 5.0,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => true,
                'nama_hotel' => 'Concorde Dar Al Khair',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => 4.0,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => true,
                'nama_hotel' => 'Abraj Tabah',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => 4.0,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => true,
                'nama_hotel' => 'Al Ansar Golden Tulip',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => 4.0,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => true,
                'nama_hotel' => 'Andalus Plas 3',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => 3.0,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => true,
                'nama_hotel' => 'Kayan International',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => 3.0,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => true,
                'nama_hotel' => 'Durrat Al Eiman',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => 3.0,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => true,
                'nama_hotel' => 'ODST',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => 3.0,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => true,
                'nama_hotel' => 'Al Marsa',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => 3.0,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => true,
                'nama_hotel' => 'Nusuk Al Eiman',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => 3.0,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => true,
                'nama_hotel' => 'Grand Zowar',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => 3.0,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => true,
                'nama_hotel' => 'Qasr Al Ansar Golden Tulip',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => 3.0,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => true,
                'nama_hotel' => 'Tanpa Hotel Madinah',
                'kota_id' => $kotaId,
                'jarak_ke_masjid' => '',
                'bintang' => null,
                'alamat' => '',
                'jam_checkin_mulai' => null,
                'jam_checkin_berakhir' => null,
                'jam_checkout_mulai' => null,
                'jam_checkout_berakhir' => null,
                'latitude' => null,
                'longitude' => null,
                'deskripsi' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        foreach ($hotels as $row) {
            $exists = DB::table('hotel_m')
                ->where('nama_hotel', $row['nama_hotel'])
                ->where('kota_id', $row['kota_id'])
                ->exists();
            if (!$exists) {
                DB::table('hotel_m')->insert($row);
            }
        }
    }
}

