/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/base/button/Button.vue')['default']
    Card: typeof import('./src/components/base/card/Card.vue')['default']
    Field: typeof import('./src/components/base/form/Field.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Input: typeof import('./src/components/base/form/Input.vue')['default']
    Label: typeof import('./src/components/base/form/Label.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Modal: typeof import('./src/components/base/modal/Modal.vue')['default']
    Placeload: typeof import('./src/components/base/loader/Placeload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('./src/components/base/form/Textarea.vue')['default']
  }
}
